### ISSUE TITLE
Can't play video from local storage

### ISSUE THREAD

**Issue by Bekakk** [brucetoo/ListVideoPlay#5]
Hi
I can't play video from local storage.Here is my source

`        final String filePath = Environment.getExternalStorageDirectory() + "/myfolder/590.mp4";

                        mVideoPlayerManager.playNewVideo(new CurrentItemMetaData(0, getRootView()), mVideoPlayerView,
                                filePath);`
Video's url is correct in my storage but I can't play video with your player
How i can solve my problem?
Thanks

**Comment by brucetoo** [comment]
Local related code had been removed.

**Comment by Bekakk** [comment]
Why ?
In my project  I have two option,Play video from URL or play from storage And i would to use your library in both situation

**Comment by brucetoo** [comment]
Sorry, i just check out that assets file is not support rather than Local file, so test "/storage/emulated/0/DCIM/Camera/video.mp4" is work as you wanted in my lib. BTW, you need check out demo [ListSupportFragment](https://github.com/brucetoo/ListVideoPlay/blob/HEAD/app/src/main/java/com/brucetoo/listvideoplay/demo/ListSupportFragment.java) and test

**Comment by Bekakk** [comment]
Thanks your attention
I'll test it Monday morning
Thanks

**Comment by Bekakk** [comment]
I tried it but I have exception 
 java.lang.RuntimeException: java.io.IOException: setDataSource failed.

**Comment by brucetoo** [comment]
can offer me more information? i check twice and still work fine in demo

**Comment by Bekakk** [comment]
Please share my your email or another contact information.I'll share details

**Comment by brucetoo** [comment]
brucetoo14@gmail.com
